#!/bin/bash

if [ -f /etc/ufw/before.rules ]; then
    # Backup existing before.rules file
    mv /etc/ufw/before.rules /etc/ufw/before.rules.bak
    echo "Existing /etc/ufw/before.rules backed up to /etc/ufw/before.rules.bak"
fi